# Site settings
title: zerojetlag
email: zerojetlag@gmail.com
description: "精神病末期"
baseurl: ""
url: ""
twitter_username: zerojetlag
github_username:  zerojetlag

# Build settings
markdown: kramdown
permalink: pretty

paginate: 5
comments: true