# Site settings
title: zerojetlag
email: zerojetlag@gmail.com
description: "A professional psyco"
baseurl: "http://zerojetlag.github.io"
url: "http://zerojetlag.github.io"
twitter_username: zerojetlag
github_username:  zerojetlag

# Build settings
markdown: kramdown
permalink: pretty
