# Site settings
title: zerojetlag
email: zerojetlag@gmail.com
description: "A professional psyco"
baseurl: ""
url: "http://www.zerojetlag.com/"
twitter_username: zerojetlag
github_username:  zerojetlag

# Build settings
markdown: kramdown
permalink: pretty

paginate: 5
comments: true