# Site settings
title: zerojetlag
email: zerojetlag@gmail.com
description: "A professional psyco"
baseurl: ""
url: "http://zerojetlag.com"
twitter_username: zerojetlag
github_username:  zerojetlag

# Build settings
markdown: kramdown
permalink: pretty
